/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.bank.menu;

import com.bank.exceptions.InvalidAccountTypeException;
import com.bank.models.Account;
import com.bank.models.Bank;
import com.bank.models.Checking;
import com.bank.models.Customer;
import com.bank.models.Savings;
import java.math.BigDecimal;
import java.math.RoundingMode;
import javax.swing.JOptionPane;

/**
 *
 * @author chihoang
 */
public class AddAccountMenu extends javax.swing.JDialog {
  
  private Bank bank; 

    /**
     * Creates new form AddAccountMenu
     */
    public AddAccountMenu(java.awt.Frame parent, boolean modal, Bank bank) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        this.bank = bank;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        firstNameLabel = new javax.swing.JLabel();
        firstNameField = new javax.swing.JTextField();
        lastNameLabel = new javax.swing.JLabel();
        lastNameField = new javax.swing.JTextField();
        ssnLabel = new javax.swing.JLabel();
        ssnField = new javax.swing.JTextField();
        depositLabel = new javax.swing.JLabel();
        depositField = new javax.swing.JTextField();
        typeLabel = new javax.swing.JLabel();
        typeBox = new javax.swing.JComboBox<>();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        jTextField6.setText("jTextField6");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(6, 2, 5, 5));

        firstNameLabel.setText("First Name:");
        getContentPane().add(firstNameLabel);
        getContentPane().add(firstNameField);

        lastNameLabel.setText("Last Name:");
        getContentPane().add(lastNameLabel);
        getContentPane().add(lastNameField);

        ssnLabel.setText("Social Security Number:");
        getContentPane().add(ssnLabel);
        getContentPane().add(ssnField);

        depositLabel.setText("Initial Deposit");
        getContentPane().add(depositLabel);
        getContentPane().add(depositField);

        typeLabel.setText("Account Type");
        getContentPane().add(typeLabel);

        typeBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Checking", "Savings" }));
        typeBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeBoxActionPerformed(evt);
            }
        });
        getContentPane().add(typeBox);

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        getContentPane().add(okButton);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        getContentPane().add(cancelButton);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void typeBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeBoxActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
      
      StringBuilder warnings = new StringBuilder();
      String firstName = "", lastName = "", ssn = "";
      double initialDeposit = 0.0;
      
      // Verify first name
      if (firstNameField.getText().isEmpty()) {
        warnings.append("First name must not be empty.\n");
      } else {
        firstName = firstNameField.getText();
      }
      // Verify last name
      if (lastNameField.getText().isEmpty()) {
        warnings.append("Last name must not be empty.\n");
      } else {
        lastName = lastNameField.getText();
      }
      // Verify ssn 123-45-6789
      if (!ssnField.getText().matches("\\d{3}-?\\d{2}-?\\d{4}")) {            
        warnings.append("Social security number is not valid. (Format: 123-45-6789)\n");
      } else {
        ssn = ssnField.getText().replace("-", "");
      }
      
      // Verify inital deposit
      if (depositField.getText().isEmpty()) {
        warnings.append("Initial deposit must not be empty.\n");
      } else {
        try {
          initialDeposit = round(Double.parseDouble(depositField.getText()), 2);
        } catch (NumberFormatException e) {
          warnings.append("Initial deposit must be a number.\n");
        }
      }
      
      // Display any warning message
      if (warnings.length() > 0) {
        JOptionPane.showMessageDialog(this, warnings.toString(), "Input Error", JOptionPane.WARNING_MESSAGE);
      } else { // Or create an account
        Account account = null;
        if (typeBox.getSelectedItem().toString().equalsIgnoreCase("Checking")) {
          account = new Checking();
        } else if (typeBox.getSelectedItem().toString().equalsIgnoreCase("Savings")) {
          account = new Savings();
        } else {
          System.out.println("Shouldn't be here");
        }
        
        System.out.println("account info " + account.getBalance() + " " + account.getInterest());
        Customer customer = new Customer(firstName, lastName, ssn, account);
        bank.addCustomer(customer);
        
        this.dispose();
      }
      
      
    }//GEN-LAST:event_okButtonActionPerformed
    
    public static double round(double value, int places) {
      if (places < 0) throw new IllegalArgumentException();

      BigDecimal bd = new BigDecimal(value);
      bd = bd.setScale(places, RoundingMode.HALF_UP);
      return bd.doubleValue();
    }
    
    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
      this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField depositField;
    private javax.swing.JLabel depositLabel;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JButton okButton;
    private javax.swing.JTextField ssnField;
    private javax.swing.JLabel ssnLabel;
    private javax.swing.JComboBox<String> typeBox;
    private javax.swing.JLabel typeLabel;
    // End of variables declaration//GEN-END:variables
}
