/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.bank.menu;

import com.bank.exceptions.InsufficientFundsException;
import com.bank.exceptions.InvalidAmountException;
import com.bank.models.Bank;
import com.bank.models.Customer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author chihoang
 */
public class WithdrawMenu extends javax.swing.JDialog {

  private Customer customer;
  /**
   * Creates new form WithdrawMenu
   */
  public WithdrawMenu(java.awt.Frame parent, boolean modal, Customer customer) {
    super(parent, modal);
    initComponents();
    setLocationRelativeTo(parent);
    this.customer = customer;
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    withdrawLabel = new javax.swing.JLabel();
    withdrawField = new javax.swing.JTextField();
    withdrawButton = new javax.swing.JButton();
    cancelButton = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Withdrawal Menu");
    getContentPane().setLayout(new java.awt.GridLayout(2, 2, 5, 5));

    withdrawLabel.setText("Withdraw Amount");
    getContentPane().add(withdrawLabel);

    withdrawField.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        withdrawFieldActionPerformed(evt);
      }
    });
    getContentPane().add(withdrawField);

    withdrawButton.setText("Withdraw");
    withdrawButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        withdrawButtonActionPerformed(evt);
      }
    });
    getContentPane().add(withdrawButton);

    cancelButton.setText("Cancel");
    cancelButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cancelButtonActionPerformed(evt);
      }
    });
    getContentPane().add(cancelButton);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void withdrawFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawFieldActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_withdrawFieldActionPerformed

  private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
    this.dispose();
  }//GEN-LAST:event_cancelButtonActionPerformed

  private void withdrawButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawButtonActionPerformed
    StringBuilder warnings = new StringBuilder();
    // Verify the withdraw is not empty
    if (withdrawField.getText().isEmpty()) {
      warnings.append("Withdraw amount is required\n");
    } else {
      double amount = 0.0;
      
      try {
        amount = Bank.round(Double.parseDouble(withdrawField.getText()), 2);
        int result = JOptionPane.showConfirmDialog(this, "Withdraw an amount of $" + String.format("%.2f", amount) 
                + " from the account?\nFee: $" + String.format("%.2f", customer.getAccount().getTransactionfee()));
        
        if (result == JOptionPane.OK_OPTION) {
          try {
            // Make the withdraw
            customer.getAccount().withdraw(amount);
            this.dispose();
            JOptionPane.showMessageDialog(this, "Withdraw an amount of $" + String.format("%.2f", amount)
                + " with a fee of $" + String.format("%.2f", customer.getAccount().getTransactionfee()));
          } catch (InsufficientFundsException ex) {
            warnings.append("Insufficient funds to complete transaction\n");
          }
        }
      } catch (NumberFormatException e) {
        warnings.append("Withdraw must be a number.\n");
      }
    }
    
    // Verify the withdraw is a positive number
      
    if (warnings.length() > 0) {
      JOptionPane.showMessageDialog(this, warnings.toString(), "Withdraw Warnings", JOptionPane.WARNING_MESSAGE);
    }
  }//GEN-LAST:event_withdrawButtonActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton cancelButton;
  private javax.swing.JButton withdrawButton;
  private javax.swing.JTextField withdrawField;
  private javax.swing.JLabel withdrawLabel;
  // End of variables declaration//GEN-END:variables
}
